// <auto-generated />
// AUTO-GENERATED FILE - DO NOT MODIFY
// Generated from {{.Filename}}
{{template "SIMPLECOMMENTS" .Comments }}

using System;
using System.Collections.Generic;
{{range usings}}using {{.}};
{{end}}
namespace {{index .Namespaces "csharp"}}
{ {{range $k, $s := .Services}}{{if $k}}
{{end}}
{{setindent "\t"}}{{template "COMMENTS" .Comments }}{{template "ATTRS" .Attributes}}	[System.CodeDom.Compiler.GeneratedCode("Babel", "")]
	public interface I{{.Name}}
	{ {{range .Methods}}
{{setindent "\t\t"}}{{template "METHODCOMMENTS" .}}{{template "ATTRS" .Attributes}}		{{formatType .Returns}} {{toPascalCase .Name}}({{range $i, $x := .Parameters}}{{if $i}}, {{end}}{{formatType .Type}} {{.Name}}{{end}});
{{end}}	}
{{setindent "\t"}}{{template "COMMENTS" .Comments }}{{template "ATTRS" .Attributes}}	[System.CodeDom.Compiler.GeneratedCode("Babel", "")]
	public interface I{{.Name}}Async
	{ {{range .Methods}}
{{setindent "\t\t"}}{{template "METHODCOMMENTS" .}}{{template "ATTRS" .Attributes}}		{{if isVoid .Returns}}System.Threading.Tasks.Task{{else}}System.Threading.Tasks.Task<{{formatType .Returns}}>{{end}} {{toPascalCase .Name}}Async({{range $i, $x := .Parameters}}{{if $i}}, {{end}}{{formatType .Type}} {{.Name}}{{end}});
{{end}}	}{{end}}
}
