// <auto-generated />
// AUTO-GENERATED FILE - DO NOT MODIFY
// Generated from {{.Filename}}
{{template "SIMPLECOMMENTS" .Comments }}

var BABELRPC = require('babelrpc');

//require('./')
{{range usings}}require('{{.}}');
{{end}}{{$ns := index .Namespaces "js"}}
var ns = BABELRPC.utils.namespace(global, '{{$ns}}');{{range .Services}}{{$cls := .Name}}
{{template "COMMENTS" .Comments }}
var client = function(baseUrl, timeoutSeconds, jsonRpc)
{
	var client = new BABELRPC.Babel.client(baseUrl, timeoutSeconds, jsonRpc);
	var that = this;

{{range $i, $m := .Methods}}
{{setindent "\t"}}{{template "METHODCOMMENTS" .}}	this.{{toCamelCase .Name}} = function({{range $i, $v := .Parameters}}{{toCamelCase .Name}}, {{end}}callback){
		client.sendRequest("{{$ns}}.{{$cls}}", "{{.Name}}", { {{range $i, $v := .Parameters}}"{{.Name}}": {{.Name}}{{if last $i $m.Parameters | not}}, {{end}}{{end}} }, callback );			
	}
{{end}}
}

ns['{{.Name}}'] = client; 
{{end}}
