// <auto-generated />
// AUTO-GENERATED FILE - DO NOT MODIFY
// Generated from {{.Filename}}
{{template "SIMPLECOMMENTS" .Comments }}

var BABELRPC = require("babelrpc")

{{range usings}}require('{{.}}');
{{end}}

var ns = BABELRPC.utils.namespace(global, '{{index .Namespaces "js"}}');

{{range .Enums}}{{template "COMMENTS" .Comments }}
ns['{{.Name}}'] = {
{{range $i,$v := .Values}}{{if $i}},
{{end}}	"{{.Name}}" : {{formatValue .}}{{end}}
}
{{end}}
{{range .Consts}}
{{template "COMMENTS" .Comments }}
ns['{{.Name}}'] ={
{{range $i,$v := .Values}}{{if $i}},
{{end}}	"{{.Name}}" : {{formatValue .}}{{end}}
}
{{end}}
{{range $is, $xs :=  .Structs}}
{{template "COMMENTS" .Comments }}
{{template "ATTRS" .Attributes}}ns['{{.Name}}'] = function()
{

{{range .Fields}}{{template "COMMENTS" .Comments }}{{template "ATTRS" .Attributes}}{{if .Initializer}}
	this.{{.Name}} = {{cast .Type}}{{formatValue .Initializer}};{{else if .Type.IsList}}
	this.{{.Name}} = [];{{else if .Type.IsMap}}
	this.{{.Name}} = {};{{else}}
	this.{{.Name}} = null;{{end}}
{{end}}
	{{if .Extends}}{{fullNameOf .Extends}}.call(this);{{end}}

	this.toString = function(){
		return JSON.tostring(this);
	}
}

{{if .Extends}}BABELRPC.utils.extend(ns['{{.Name}}'], {{fullNameOf .Extends}});{{end}}
{{end}}

