// <auto-generated />
// AUTO-GENERATED FILE - DO NOT MODIFY
// Generated from {{.Filename}}
{{template "SIMPLECOMMENTS" .Comments }}

var BABELRPC = require('babelrpc');
var server = require('./service.js');

{{range usings}}require('{{.}}');{{end}}{{$x := index .Namespaces "js"}}{{range .Services}}
{{template "COMMENTS" .Comments }}{{$cls := .Name}}{{setindent "\t"}}
var {{$cls}} = function() {

{{range $i, $m := .Methods}}
{{template "METHODCOMMENTS" .}}	this.{{.Name}} = function({{range $i, $v := .Parameters}}{{toCamelCase .Name}}, {{end}}callback){
		throw new Error('"{{.Name}}" not implimented');
	};{{end}}
}
{{end}}

module.exports = exports = new function(){ 
	this.jsonrpc = new function(){ {{range $i, $v := .Services}}
	 	this.{{.Name}} = function(){
	 		return server.{{.Name}}.jsonrpc.createServer( new {{.Name}}() ); 
	 	}{{end}}
	};
	this.api = new function(){ {{range $i, $v := .Services}}
	 	this.{{.Name}} = function(baseUrl){
	 		return server.{{.Name}}.api.createServer( baseUrl, new {{.Name}}() ); 
	 	}{{end}}
	}
}
