// Code generated by "stringer -type=HttpMethod"; DO NOT EDIT.

package rest

import "strconv"

const _HttpMethod_name = "GETPUTPOSTDELETEOPTIONSHEADPATCH"

var _HttpMethod_index = [...]uint8{0, 3, 6, 10, 16, 23, 27, 32}

func (i HttpMethod) String() string {
	if i < 0 || i >= HttpMethod(len(_HttpMethod_index)-1) {
		return "HttpMethod(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _HttpMethod_name[_HttpMethod_index[i]:_HttpMethod_index[i+1]]
}
