// generated by stringer -type=HttpMethod; DO NOT EDIT

package rest

import "fmt"

const _HttpMethod_name = "GETPUTPOSTDELETEOPTIONSHEADPATCH"

var _HttpMethod_index = [...]uint8{0, 3, 6, 10, 16, 23, 27, 32}

func (i HttpMethod) String() string {
	if i < 0 || i+1 >= HttpMethod(len(_HttpMethod_index)) {
		return fmt.Sprintf("HttpMethod(%d)", i)
	}
	return _HttpMethod_name[_HttpMethod_index[i]:_HttpMethod_index[i+1]]
}
