// Code generated by "stringer -type=ListFmt"; DO NOT EDIT.

package rest

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NONE-0]
	_ = x[CSV-1]
	_ = x[SSV-2]
	_ = x[TSV-3]
	_ = x[PIPES-4]
	_ = x[MULTI-5]
}

const _ListFmt_name = "NONECSVSSVTSVPIPESMULTI"

var _ListFmt_index = [...]uint8{0, 4, 7, 10, 13, 18, 23}

func (i ListFmt) String() string {
	if i < 0 || i >= ListFmt(len(_ListFmt_index)-1) {
		return "ListFmt(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ListFmt_name[_ListFmt_index[i]:_ListFmt_index[i+1]]
}
