// generated by stringer -type=ListFmt; DO NOT EDIT

package rest

import "fmt"

const _ListFmt_name = "NONECSVSSVTSVPIPESMULTI"

var _ListFmt_index = [...]uint8{0, 4, 7, 10, 13, 18, 23}

func (i ListFmt) String() string {
	if i < 0 || i+1 >= ListFmt(len(_ListFmt_index)) {
		return fmt.Sprintf("ListFmt(%d)", i)
	}
	return _ListFmt_name[_ListFmt_index[i]:_ListFmt_index[i+1]]
}
