// Code generated by "stringer -type=ParmIn"; DO NOT EDIT.

package rest

import "strconv"

const _ParmIn_name = "QUERYHEADERPATHFORMDATABODY"

var _ParmIn_index = [...]uint8{0, 5, 11, 15, 23, 27}

func (i ParmIn) String() string {
	if i < 0 || i >= ParmIn(len(_ParmIn_index)-1) {
		return "ParmIn(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ParmIn_name[_ParmIn_index[i]:_ParmIn_index[i+1]]
}
