// generated by stringer -type=ParmIn; DO NOT EDIT

package rest

import "fmt"

const _ParmIn_name = "QUERYHEADERPATHFORMDATABODY"

var _ParmIn_index = [...]uint8{0, 5, 11, 15, 23, 27}

func (i ParmIn) String() string {
	if i < 0 || i+1 >= ParmIn(len(_ParmIn_index)) {
		return fmt.Sprintf("ParmIn(%d)", i)
	}
	return _ParmIn_name[_ParmIn_index[i]:_ParmIn_index[i+1]]
}
